#!D:\semester 7\mlops\Project\secondtry\MLOPS_FINAL_PROJECT_NewsData_API\venv311\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
